### ISSUE TITLE
Invalid Podfile file: no implicit conversion of nil into String react-native

### ISSUE THREAD

**Issue by sercanislekler** [sercanislekler/react-native#1]
Hello,

When I run the pod install method in the ios folder in my React-Native project, I get the following error.

I used expo in this project. I run the Expo prebuild command successfully. 

Afterwards, when I want to run the expo run:ios command, it wants to install cocoapods, but it is not successful.

I go to the ios directory and run pod install and I get the error I mentioned.

I tried the methods I found on GitHub, stackoverflow and many form pages. 

But there was no solution.

I logged all my lines one by one in the podfile.

All lines are worth it.

I would be very happy if you could help. 

Kind regards.

[!] Invalid Podfile file: no implicit conversion of nil into String.

 #  from /Users/sercan/Desktop/react/Veti/ios/Podfile:44
 #  -------------------------------------------
 #  
 >    use_react_native!(
 #      :path => config[:reactNativePath],
 #  -------------------------------------------

**Comment by abhisharma9876** [comment]
try this
https://bit.ly/3TyLBMS
If you don't have the c compliator, install it.(gcc or clang)

**Comment by sercanislekler** [comment]
.
